---
- name: Add Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew Cask packages
  homebrew_cask: name={{ item.name }}
  with_items: "{{ homebrew_cask_packages }}"

- name: Install Homebrew packages
  homebrew: name={{ item.name }} state={{ item.state | default('latest') }} install_options={{ item.install_options | default() }}
  with_items: "{{ homebrew_packages }}"

- name: Clean Homebrew
  shell: brew cleanup
